name: Push action

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Setup environment
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry --version
      
      - name: Install dependencies
        run: |
          poetry --version
          poetry install
      
      - name: Lint
        run: |
          poetry --version
          make lint
      
      - name: Test
        run: |
          poetry --version
          make tests
      
      - name: Build package
        run: |
          poetry --version
          poetry build
      
      - name: Publish to PyPI
        run: |
          poetry --version
          poetry publish -u __token__ -p ${{ secrets.PYPIPASS }}